Housecleaning

diff --git a/_dotfiles_init b/_dotfiles_init
--- a/_dotfiles_init
+++ b/_dotfiles_init
@@ -1,13 +1,13 @@
 #autoload
-# Make sure variables are defined
+# Check/Set $DOTFILES_DIR
 if [[ -z $DOTFILES_DIR ]]; then 
   echo "'$DOTFILES_DIR' is not set. This needs to be defined before the script can continue"
   exit 1
 fi
 echo "'$DOTFILES_DIR' is set as: $DOTFILES_DIR"
 
-# Make sure $DOTFILES_URL is set
-_dotfiles_repo_url checkvar
+# Check/Set Git alias
+_dotfiles_git_alias
 
 # Create and initialize the repo
 # Check if target dir exists
@@ -17,24 +17,31 @@ if [[ ! -d $DOTFILES_DIR ]]; then
 else
   echo "$DOTFILES_DIR already exists."  
 fi
-# Check if target dir already contains a git repo
+# Check for existing git repo
 if [[ $(git rev-parse --resolve-git-dir $DOTFILES_DIR) ]]; then
   echo "$DOTFILES_DIR is already a git repo. Aborting"
-  exit 1
-fi
-
-echo "Initializing git repo in $DOTFILES_DIR"
-[[ $(_dotfiles_git_cmd init --bare -b main) ]] && echo "init complete" || echo "There was an error initializing your dotfiles repo. Aborted"; exit $?
-
-echo "Setting up remote:"
-if [[ ! $(_dotfiles_git_cmd remote add origin $DOTFILES_GIT_REMOTE_URL) ]]; then
-  echo "Error: Remote was not set successfully"
-  exit 1
+  return 1
 else
-  # Verify remote url is set
-  
-  echo "Remote set: $(_dotfiles_git_cmd ls-remote --get-url)"
+  echo "Initializing git repo in $DOTFILES_DIR"
+  _dotfiles_git_cmd init --bare -b main
+  [[ $? = 0 ]] && echo "init complete" || echo "There was an error initializing your dotfiles repo. Aborted"; return 1
 fi
-    
+
+# Check/Set Git config options
+_dotfiles_config
+
+# Check/Set $DOTFILES_URL
+_dotfiles_url
+
+# Add a file
+echo "adding .zshrc"
+_dotfiles_git add .zshrc
+echo "Committing..."
+_dotfiles_git commit -m "Initial Upload"
+echo "Pushing new repo to remote"
+_dotfiles_git push -u origin main
+
+
+
   
 
